package catch

// Entity codes
const (
	EMPTY = iota
	PLAYER
	PAWN_NORTH
	PAWN_EAST
	PAWN_SOUTH
	PAWN_WEST
	DAMAGED_ROOK
	ROOK
	DAMAGED_BISHOP_2
	DAMAGED_BISHOP_1
	BISHOP
	DAMAGED_KNIGHT_3
	DAMAGED_KNIGHT_2
	DAMAGED_KNIGHT_1
	KNIGHT
	DAMAGED_QUEEN_4
	DAMAGED_QUEEN_3
	DAMAGED_QUEEN_2
	DAMAGED_QUEEN_1
	QUEEN
	KING
	SHADOW_PLAYER
	SHADOW_PAWN
	SHADOW_ROOK
	SHADOW_BISHOP
	SHADOW_KNIGHT
	SHADOW_QUEEN
	SHADOW_KING
)

const ZERO = EMPTY

// Game field parameters
const (
	NOWHERE    = -1
	FIELD_SIDE = DAMAGED_BISHOP_1
	FIELD_SIZE = FIELD_SIDE * FIELD_SIDE
	LAST_INDEX = FIELD_SIDE - 1
	CENTER     = FIELD_SIDE / 2
)

const (
	PLAYER_HP_MAX = DAMAGED_BISHOP_1
)

// Directions
const (
	NORTH        = PAWN_NORTH
	EAST         = PAWN_EAST
	SOUTH        = PAWN_SOUTH
	WEST         = PAWN_WEST
	NO_DIRECTION = EMPTY
)
